#!/usr/bin/env bash
# fetch-iso.sh — select a Windows 11 Arm64 ISO for the recipe.
#
# Microsoft publishes official Windows 11 Arm64 ISOs, but the final
# download URL is browser/session generated and not stable enough for a
# brittle scraper. This helper validates VMH_WIN11_ARM_ISO when supplied;
# otherwise it prints the official manual download path.
#
# Target: ./build/win11-arm64.iso
#
# Override with VMH_WIN11_ARM_ISO=/path/to/existing.iso to skip the
# manual step entirely.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
BUILD_DIR="${SCRIPT_DIR}/build"
ISO_PATH="${BUILD_DIR}/win11-arm64.iso"
OFFICIAL_URL="https://www.microsoft.com/en-us/software-download/windows11arm64"

if [[ -n "${VMH_WIN11_ARM_ISO:-}" ]]; then
  echo "fetch-iso: VMH_WIN11_ARM_ISO=${VMH_WIN11_ARM_ISO} — skipping download."
  if [[ ! -f "${VMH_WIN11_ARM_ISO}" ]]; then
    echo "fetch-iso: error — ${VMH_WIN11_ARM_ISO} does not exist." >&2
    exit 1
  fi
  mkdir -p "${BUILD_DIR}"
  ln -sf "${VMH_WIN11_ARM_ISO}" "${ISO_PATH}"
  echo "fetch-iso: using existing ISO at ${VMH_WIN11_ARM_ISO}"
  echo "fetch-iso: linked ${ISO_PATH}"
  exit 0
fi

if [[ -f "${ISO_PATH}" ]]; then
  echo "fetch-iso: ISO already present at ${ISO_PATH} — skipping download."
  echo "fetch-iso: delete it and re-run to refresh."
  exit 0
fi

mkdir -p "${BUILD_DIR}"

cat <<'EOF'
fetch-iso: manual Microsoft ISO download required.

Microsoft now publishes official Windows 11 Arm64 ISOs. The final ISO URL is
generated by Microsoft's browser flow and may include short-lived tokens, so
this script deliberately does not scrape it.

Manual step:

  1. Open https://www.microsoft.com/en-us/software-download/windows11arm64
  2. Select the Windows 11 Arm64 ISO, language, and edition.
  3. Download the ISO.
  4. Either move/link it to ./build/win11-arm64.iso, or re-run this script with:

       VMH_WIN11_ARM_ISO=/path/to/Win11_Arm64.iso ./fetch-iso.sh

EOF

echo "fetch-iso: official page: ${OFFICIAL_URL}"
echo "fetch-iso: target ISO path: ${ISO_PATH}"
exit 2
